### ISSUE TITLE
Only one [youversion] tag allowed per paragraph?

### ISSUE THREAD

**Issue by iamaaronmartin** [erikreagan/er.youversion.ee_addon#1]
I'm having only my first and last tag rendered as a YouVersion link per paragraph. Multiple verses, each wrapped in it's own [youversion] open and close, combine together to form a single bad link.

**Comment by erikreagan** [comment]
Okay I'll check that out. Thanks for letting me know!

**Comment by iamaaronmartin** [comment]
No problem. Great plugin.

**Comment by erikreagan** [comment]
I've updated the plugin to 1.2.0 and you can now link multiple scriptures by using a comma followed by a space like this:

[youversion]John 3:16, 1 Timothy 1:7[/youversion]

Let me know if you have any issues with it. Thanks :)

**Comment by iamaaronmartin** [comment]
Works perfectly. Nice work.
